name: 'Gallery Standard Validation'
description: 'Validate the standard of the gallery'
inputs:
  templatePath:
    description: 'The path of target template to validate'
    required: true
    default: '.'
outputs:
  resultFile:
    description: "A file path to a results file."
    value: ${{ steps.run_validation.outputs.resultFile}}
runs:
  using: "composite"
  steps:
    - name: Extract topics
      id: extract_repo_info
      run: |
        repository=${{ env.REPOSITORY || github.repository }}
        topics_list=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repository/topics | jq -r '.names | join(",")')
        echo "topics=\"$topics_list\"" >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

    - name: Run Microsoft Security DevOps Analysis
      uses: microsoft/security-devops-action@v1
      id: msdo
      with:
        tools: templateanalyzer
      env:
        GDN_TEMPLATEANALYZER_ANALYZEDIRECTORY: ${{ inputs.templatePath }}

    - name: Set environment name with timestamp
      id: set_env_name
      run: |
        current_time=$(date +%m%d%H%M)
        azure_env_name="${{ env.AZURE_ENV_NAME }}-$current_time"
        echo "AZURE_ENV_NAME=$azure_env_name" >> $GITHUB_ENV
        echo "azure_env_name is $azure_env_name"
      shell: bash
      env:
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}

    - name: Install AZD
      uses: Azure/setup-azd@v1.0.0

    - name: Log in with Azure (Federated Credentials)
      if: ${{ env.AZURE_CLIENT_ID != '' }}
      run: |
        azd auth login --client-id "${{ env.AZURE_CLIENT_ID }}" --federated-credential-provider "github" --tenant-id "${{ env.AZURE_TENANT_ID }}"
      shell: bash
      env:
        AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}

    - name: Run validation
      id: run_validation
      working-directory: ${{ inputs.templatePath }}
      run: |
        python ${{ github.action_path }}/src/gallery_validate.py . --debug --azdup --azddown --topics ${{ env.TOPICS }} --msdoresult ${{ steps.msdo.outputs.sarifFile }} --output ${{ runner.temp }}/output.log
        output_link=$(realpath ${{ runner.temp }}/output.log)
        echo "resultFile is $output_link"
        echo "resultFile=$output_link" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TOPICS: ${{ env.topics }}
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        CREATE_ROLE_FOR_USER: false
        AZURE_PRINCIPAL_TYPE: "ServicePrincipal"