name: 'Gallery Standard Validation'
description: 'Validate the standard of the gallery'
inputs:
  workingDirectory:
    description: 'The path of target template to validate'
    required: true
    default: '.'
  validatePaths:
    description: 'Comma-separated list of paths to validate'
    required: false
  topics:
    description: 'Comma-separated list of topics to check'
    required: false
  validateAzd:
    description: 'Run azd up and azd down for validation'
    required: true
    default: 'true'
  useDevContainer:
    description: 'Use dev container for validation'
    required: true
    default: 'true'
  securityAction:
    description: 'Run security action validation'
    required: true
    default: ''
    options:
      - 'PSRule'
outputs:
  resultFile:
    description: "A file path to a results file."
    value: ${{ steps.set_output.outputs.resultFile }}
runs:
  using: "composite"
  steps:
    - name: Check for .devcontainer config
      id: check_devcontainer
      if : ${{ inputs.useDevContainer == 'true' }}
      run: |
        if [ ! -f "${{ inputs.workingDirectory }}/.devcontainer/devcontainer.json" ]; then
          echo "Error: devcontainer config does not exist but useDevContainer is set to true."
          exit 1
        fi
      shell: bash
        
    - name: Extract topics
      id: extract_repo_info
      if: ${{ inputs.topics != '' }}
      run: |
        repository_name=${{ env.REPOSITORY_NAME || github.repository }}
        topics_list=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" repos/$repository_name/topics | jq -r '.names | join(",")')
        echo "TOPICS=\"$topics_list\"" >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    
    # TODO: check security with PSRule or msdo

    - name: Set environment name with timestamp
      id: set_env_name
      if: ${{ inputs.validateAzd == 'true' }}
      run: |
        current_time=$(date +%m%d%H%M)
        azure_env_name="${{ env.AZURE_ENV_NAME }}-$current_time"
        echo "AZURE_ENV_NAME=$azure_env_name" >> $GITHUB_ENV
        echo "azure_env_name is $azure_env_name"
      shell: bash
      env:
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}

    - name: Copy validator into devcontainer
      if: ${{ inputs.useDevContainer == 'true' }}
      run: |
        mkdir -p ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}
        cp -r ${{ github.action_path }}/src ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}/src
        cp ${{ github.action_path }}/requirements.txt ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}/requirements.txt
        env > ${{ inputs.workingDirectory }}/tva_${{ github.run_id }}/env_variables.txt
      shell: bash

    - uses: actions/github-script@v6
      id: script
      if: ${{ inputs.useDevContainer == 'true' && inputs.validateAzd == 'true' }}
      with:
        debug: true
        script: |
          const token = process.env['ACTIONS_RUNTIME_TOKEN']
          const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
          const aadToken = await core.getIDToken('api://AzureADTokenExchange');
          core.setOutput('TOKEN', token.trim())
          core.setOutput('AAD_TOKEN', aadToken.trim())
          core.setOutput('ID_TOKEN_URL', runtimeUrl.trim())

    # A workaround to those template that using Docker 
    - name: Start Docker
      if: ${{ inputs.useDevContainer == 'true' && inputs.validateAzd == 'true' }}
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          if find . -type f -iname 'dockerfile' | grep -q .; then
            sudo service docker start
          fi
        subFolder: ${{ inputs.workingDirectory }}
      continue-on-error: true

    - name: Login azd in devcontainer
      id: azd-login
      if: ${{ inputs.useDevContainer == 'true' && inputs.validateAzd == 'true' }}
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          azd auth login --client-id "${{ env.AZURE_CLIENT_ID }}" --federated-credential-provider "github" --tenant-id "${{ env.AZURE_TENANT_ID }}"
          az login --service-principal -u "${{ env.AZURE_CLIENT_ID }}" --federated-token $AZURE_AD_TOKEN --tenant "${{ env.AZURE_TENANT_ID }}"
        subFolder: ${{ inputs.workingDirectory }}
        env: |
          ACTIONS_ID_TOKEN_REQUEST_URL=${{ steps.script.outputs.ID_TOKEN_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN=${{ steps.script.outputs.TOKEN }}
          AZURE_AD_TOKEN=${{ steps.script.outputs.AAD_TOKEN }}
      continue-on-error: true
      
    - name: Setup Python in devcontainer
      id: setup-python
      if: ${{ inputs.useDevContainer == 'true' }}
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          if ! command -v python &> /dev/null; then
            echo "python not found, installing python..."
            sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-venv
          fi
          python3 -m venv .venv --system-site-packages
          source .venv/bin/activate
          python3 -m pip install -r tva_${{ github.run_id }}/requirements.txt;
        subFolder: ${{ inputs.workingDirectory }}
    
    - name: Run validation
      id: validation
      if: ${{ inputs.useDevContainer == 'true' }}
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          source .venv/bin/activate
          if [ -f tva_${{ github.run_id }}/env_variables.txt ]; then
            while IFS= read -r line; do
              var_name=$(echo "$line" | cut -d'=' -f1)
              if [ -z "${!var_name}" ]; then
                export "$line"
              fi
            done < tva_${{ github.run_id }}/env_variables.txt
          fi
          if [ "${{ inputs.runAzdUp }}" = "true" ]; then
            python3 tva_${{ github.run_id }}/src/gallery_validate.py . --output tva_${{ github.run_id }}/output.log --debug --topics "$TOPICS" --azdup --azddown
          else
            python3 tva_${{ github.run_id }}/src/gallery_validate.py . --output tva_${{ github.run_id }}/output.log --debug --topics "$TOPICS"
          fi
        subFolder: ${{ inputs.workingDirectory }}
        env: |
          ACTIONS_ID_TOKEN_REQUEST_URL=${{ steps.script.outputs.ID_TOKEN_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN=${{ steps.script.outputs.TOKEN }}
          AZURE_CLIENT_ID=${{ env.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID=${{ env.AZURE_TENANT_ID }}
          AZURE_ENV_NAME=${{ env.AZURE_ENV_NAME }}
          AZURE_LOCATION=${{ env.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID=${{ env.AZURE_SUBSCRIPTION_ID }}
          CREATE_ROLE_FOR_USER=false
          AZURE_PRINCIPAL_TYPE=ServicePrincipal
          FORCE_TERRAFORM_REMOTE_STATE_CREATION=false
    
    - name: Send output to main workflow
      id: send_output
      if: ${{ inputs.useDevContainer == 'true' }}
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          cat tva_${{ github.run_id }}/output.log
        subFolder: ${{ inputs.workingDirectory }}

    - name: Install AZD
      if: ${{ inputs.useDevContainer == 'false' }}
      uses: Azure/setup-azd@v1.0.0

    - name: Log in with Azure (Federated Credentials)
      if: ${{ env.AZURE_CLIENT_ID != '' && inputs.useDevContainer == 'false' }}
      run: |
        azd auth login --client-id "${{ env.AZURE_CLIENT_ID }}" --federated-credential-provider "github" --tenant-id "${{ env.AZURE_TENANT_ID }}"
      shell: bash
      env:
        AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}

    - name: Run validation
      id: run_validation
      if: ${{ inputs.useDevContainer == 'false' }}
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
        if [ "${{ inputs.runAzdUp }}" = "true" ]; then
          python ${{ github.action_path }}/src/gallery_validate.py . --debug --topics "${{ env.TOPICS }}" --output ${{ env.AZURE_ENV_NAME }}-output.log --azdup --azddown
        else
          python ${{ github.action_path }}/src/gallery_validate.py . --debug --topics "${{ env.TOPICS }}" --output ${{ env.AZURE_ENV_NAME }}-output.log
        fi
      shell: bash
      env:
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
        AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
        CREATE_ROLE_FOR_USER: false
        AZURE_PRINCIPAL_TYPE: "ServicePrincipal"

    - id: set_output
      run: |
        if [[ ${{ inputs.useDevContainer }} == 'true' ]]; then
          echo "${{ steps.send_output.outputs.runCmdOutput }}" >> ${{ env.AZURE_ENV_NAME }}-output.log
        fi
        output_link=$(realpath ${{ env.AZURE_ENV_NAME }}-output.log)
        echo "resultFile is $output_link"
        echo "resultFile=$output_link" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash 
      env:
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
